### ISSUE TITLE
Stream Data ReceiveProgress 

### ISSUE THREAD

**Issue by gitNemo** [Borvik/Winsock.Net#1]
Hello!
How to get stream data on ReceiveProgress ? Or we have to impliment it ?
Thank you

**Comment by Borvik** [comment]
Hi gitNemo,

You do not have to implement it, but ReceiveProgress was meant for updating UIs with the progress of large send/receive operations (such as updating progress bars).

To receive the data, you should look at the DataArrival event.  Take a look at the demo application to see how that was implemented.

**Comment by gitNemo** [comment]
So I will send data by chunk to simulate a streaming of an mp3 file. Because DataArrival fire when Full data are received.
Thank you again.

**Comment by Borvik** [comment]
Yes, when a file is sent (when not in Legacy mode), it is recognized upon receiving as such and saves the incoming byte stream to a temporary file raising the ReceiveProgress event at every chunk split.  Then when the file is completely received it should raise the DataArrival event and you should have access to the incoming file details, including the path to the temporary file.
